apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sCheckDeploymentNs
metadata:
  name: check-deployment-ns
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    namespace: ["default", "default2"]
