apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPrivateRepo
metadata:
  name: deployment-must-have-privaterepo
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    privaterepo: "nexus-registry-mirror.zebrastack.com/"
