apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredreplicas
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredReplicas
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            replica:
              type: integer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredreplicas

        violation[{"msg": msg, "details": {"missing_replicas": missing}}] {
          provided := input.review.object.spec.replicas
          required := input.parameters.replicas
          missing := required - provided
          missing > 0
          msg := sprintf("you must more replicas: %v", [missing])
        }
